#!/usr/bin/env python3
"""Import the Prism travel dashboard into a workspace and publish it for embedding.

Companion to ``provision_dataset.py``. The checked-in definition
(``scripts/fevm/travel_dashboard.json``) points its datasets at the FEVM catalog,
so the same textual retarget applies here.

The publish step is the part that is easy to miss: an AI/BI dashboard must be
published **with embedded credentials** for the app's scoped embed token to
render it. Published without them, the iframe prompts the viewer to log into
Databricks — which is precisely what a white-label app must never do.

Re-running is safe: a dashboard with the same name is updated in place rather
than duplicated, so the ``dashboard_id`` your config points at stays valid.

Usage:
    python scripts/deploy/provision_dashboard.py --profile personal \\
        --catalog workspace --schema prism_travel
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

_DEF = _REPO / "scripts" / "fevm" / "travel_dashboard.json"
_SOURCE_FQN = "serverless_stable_71zsua_catalog.prism_travel"
_DEFAULT_NAME = "Prism Travel Intelligence"


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Import + publish the Prism travel dashboard.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--profile", required=True, help="Databricks CLI profile")
    p.add_argument("--catalog", required=True, help="target UC catalog")
    p.add_argument("--schema", default="prism_travel", help="target UC schema")
    p.add_argument("--name", default=_DEFAULT_NAME, help="dashboard display name")
    p.add_argument("--warehouse-id", default=None, help="warehouse (default: first available)")
    p.add_argument(
        "--write-seed",
        default=None,
        metavar="PATH",
        help="also emit an asset registry retargeted at the new dashboard id "
             "(point ASSETS_SEED_FILE at it); e.g. server/assets/dashboards.personal.json",
    )
    return p.parse_args(argv)


def _write_seed(path: Path, dashboard_id: str, profile: str) -> None:
    """Re-point the asset registry at a freshly imported dashboard.

    The registry keys pages by name (``spend``, ``sustainability``) and those
    survive the import unchanged, so only the dashboard id moves. Generating this
    beats hand-copying the seed per workspace, which would fork the curated Genie
    prompts along with it.
    """
    seed = json.loads((_REPO / "server" / "assets" / "dashboards.seed.json").read_text())
    for asset in seed.get("assets", {}).values():
        asset["dashboardId"] = dashboard_id
    seed["_note"] = (
        f"GENERATED by scripts/deploy/provision_dashboard.py for profile '{profile}'. "
        f"Retargets the canonical dashboards.seed.json at dashboard {dashboard_id}. "
        "Edit the canonical seed and re-run rather than editing this file."
    )
    path.write_text(json.dumps(seed, indent=2) + "\n")
    print(f"# wrote {path.relative_to(_REPO)} (ASSETS_SEED_FILE)")


def _serialized(catalog: str, schema: str) -> str:
    raw = _DEF.read_text()
    if _SOURCE_FQN not in raw:
        raise RuntimeError(
            f"{_DEF.name} no longer references {_SOURCE_FQN} — update _SOURCE_FQN."
        )
    # The API takes the definition as a JSON *string*, not a nested object.
    return json.dumps(json.loads(raw.replace(_SOURCE_FQN, f"{catalog}.{schema}")))


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    from databricks.sdk import WorkspaceClient

    w = WorkspaceClient(profile=args.profile)
    api = w.api_client

    warehouse_id = args.warehouse_id or next(
        (wh.id for wh in w.warehouses.list() if wh.id), None
    )
    if not warehouse_id:
        raise RuntimeError("no SQL warehouse available")

    body = {
        "display_name": args.name,
        "warehouse_id": warehouse_id,
        "serialized_dashboard": _serialized(args.catalog, args.schema),
    }

    existing = next(
        (d for d in api.do("GET", "/api/2.0/lakeview/dashboards").get("dashboards", [])
         if d.get("display_name") == args.name
         and d.get("lifecycle_state") == "ACTIVE"),
        None,
    )
    if existing:
        dashboard_id = existing["dashboard_id"]
        # The etag guards against clobbering a concurrent edit and the API rejects
        # an empty one — and the *list* response omits it, so it has to be read
        # from the individual GET.
        current = api.do("GET", f"/api/2.0/lakeview/dashboards/{dashboard_id}")
        body["etag"] = current["etag"]
        api.do("PATCH", f"/api/2.0/lakeview/dashboards/{dashboard_id}", body=body)
        print(f"# updated existing dashboard {dashboard_id}")
    else:
        created = api.do("POST", "/api/2.0/lakeview/dashboards", body=body)
        dashboard_id = created["dashboard_id"]
        print(f"# created dashboard {dashboard_id}")

    api.do(
        "POST",
        f"/api/2.0/lakeview/dashboards/{dashboard_id}/published",
        body={"embed_credentials": True, "warehouse_id": warehouse_id},
    )
    print("# published with embed_credentials=true")

    if args.write_seed:
        _write_seed(Path(args.write_seed).resolve(), dashboard_id, args.profile)

    host = w.config.host.rstrip("/")
    print(f"\ndashboard_id : {dashboard_id}")
    print(f"DASHBOARD_URL: {host}/embed/dashboardsv3/{dashboard_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
